repo: "svg-icon-sets"
canvasCourse: "web-design-2"

inherit:
  - naming-restrict-live
  - git-2
  - html
  - css
  - body-margin-0
  - google-fonts

html:
  - path: "index.html"
    outline: false
    has:
      - [
          'link[href*="Overpass"]',
          "The Google Font, `Overpass` (regular & bold) is missing",
        ]
      - "i > svg > use"
      - "section"
      - "h2"
      - "h3"
      - ".icon"
    hasNot:
      - "img"
    search:
      - "Mars colonization structures"
      - "Space bubbles"
      - "Super domes"
      - "Mecha-stilts"
      - "Learn about"

css:
  - path: "css/main.css"
    has:
      - ["html", "font-family", "Overpass, sans-serif"]
      - ["html", "text-size-adjust", "100%"]
      - ["html", "-webkit-text-size-adjust", "100%"]
      - ["@38"]
    search:
      - "#fff"
      - "#ff9500"
      - "#ff5e3a"
      - 'background-image: linear-gradient\('
      - ":hover"
      - "display: grid"
      - "display: flex"

screenshots:
  - path: "index.html"
    sizes: [320, 608, 1440]
